### ISSUE TITLE
Compiled Hex File for v.0.9.8

### ISSUE THREAD

**Issue by kreefd** [RChadwick7/FreedomWavePD#7]
Hi,

i was again reading all necessary steps as i am waiting for parts arriving.
Might it be possible to upload the already compiled file for v0.9.8. ?

Thanks in advance

Kind Regards

kreefd

**Comment by RChadwick7** [comment]
If you already have the Arduino Nano, you absolutely can flash the firmware without the rest of it, but it might be hard to test that everything went OK. In general, if the flash software doesn't give an error message and you see the bar graph display while flashing, it should be good.

**Comment by kreefd** [comment]
Oh okay, thank you. It was a mistake anyway of me.
I was cloning this repo:
https://github.com/RChadwick7/FreedomWavePD.git

 as i thought thats all the files needed.


And now i saw when i click on the right side of the Mainpage on Releases 0.9.8
That i can there download the .zip which includes the other files:

This link:
https://github.com/RChadwick7/FreedomWavePD/releases/download/v0.9.8/FreedomWavePD-0.9.8.zip

**Comment by kreefd** [comment]
C:\Users\kreefd\Desktop\gloves\FreedomWavePD\Software\v0.9.8>avrdude -C avrdude.conf -v -patmega328p -carduino -p4 -b57600 -D -Uflash:w:FreedomWavePD-0.9.8.hex:i

avrdude: Version 7.2
         Copyright the AVRDUDE authors;
         see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

         System wide configuration file is C:\Users\kreefd\Desktop\gloves\FreedomWavePD\Software\v0.9.8\avrdude.conf

         Using Port                    : com4
         Using Programmer              : arduino
         Overriding Baud Rate          : 57600

avrdude part_not_found() error: AVR part 4 not found

Valid parts are:
  uc3a0512   = AT32UC3A0512       [C:\Users\kreefd\Desktop\gloves\FreedomWavePD\Software\v0.9.8\avrdude.conf:17536]
    - AT32UC3A0512-ALTR:    LQFP144,  Fmax=66 MHz, T=[-40 C, 85 C], Vcc=[1.65 V, 3.6 V]
    - AT32UC3A0512-ALTRA:   LQFP144,  Fmax=66 MHz, T=[-40 C, 85 C], Vcc=[1.65 V, 3.6 V]
    - AT32UC3A0512-ALTT:    LQFP144,  Fmax=66 MHz, T=[-40 C, 85 C], Vcc=[1.65 V, 3.6 V]
    - AT32UC3A0512-ALTTA:   LQFP144,  Fmax=66 MHz, T=[-40 C, 85 C], Vcc=[1.65 V, 3.6 V]
    - AT32UC3A0512-ALUR:    LQFP144,  Fmax=66 MHz, T=[-40 C, 85 C], Vcc=[1.65 V, 3.6 V]
    - AT32UC3A0512-ALUT:    LQFP144,  Fmax=66 MHz, T=[-40 C, 85 C], Vcc=[1.65 V, 3.6 V]
    - AT32UC3A0512-CTUR:    TFBGA144, Fmax=66 MHz, T=[-40 C, 85 C], Vcc=[1.65 V, 3.6 V]
    - AT32UC3A0512-CTUT:    TFBGA144, Fmax=66 MHz, T=[-40 C, 85 C], Vcc=[1.65 V, 3.6 V]
    - AT32UC3A0512AU-ALTRA: LQFP144,  Fmax=66 MHz, T=[-40 C, 85 C], Vcc=[1.65 V, 3.6 V]
    - AT32UC3A0512AU-ALUT:  LQFP144,  Fmax=66 MHz, T=[-40 C, 85 C], Vcc=[1.65 V, 3.6 V]
  89S51      = AT89S51            [C:\Users\kreefd\Desktop\gloves\FreedomWavePD\Software\v0.9.8\avrdude.conf:2954]
  
  
  One of the first lines says:
  
  avrdude part_not_found() error: AVR part 4 not found
  
  but there seems configurations taken place afterwards and no more errors occur.

**Comment by RChadwick7** [comment]
It's probably good, as long as you saw the bargraph go across as it was programming. Some Arduinos use 57600baud and others 115kbaud. The install script tries one, then the other. If the first one isn't the right baud rate, you'll see an error. As long as one works, you're good.

**Comment by kreefd** [comment]
Unfortunately i don't see a bar graph in the terminal. 
Yes i had to use the 57600 baud that gives the response above with the 
first line : 

avrdude part_not_found() error: AVR part 4 not found

I forgot to mention i had to change the default serial port in the **avrdude.conf**

`default_serial     = "com1";`
 to
`default_serial     = "com4";`

as my device manager shows **com4** for the arduino .


Also i had to change the line :
`avrdude -C avrdude.conf -v -patmega328p -carduino **-P4** -b57600 -D -Uflash:w:FreedomWavePD-0.9.8.hex:i`

**to**

`avrdude -C avrdude.conf -v -patmega328p -carduino **-p4** -b57600 -D -Uflash:w:FreedomWavePD-0.9.8.hex:i`

small **-p** instead of **-P**.

I dont know why but with **-P4** it says :

```
C:\Users\kreefd\Desktop\gloves\FreedomWavePD\Software\FreedomWavePD-0.9.8>avrdude -C avrdude.conf -v -patmega328p -carduino -P4 -b57600 -D -Uflash:w:FreedomWavePD-0.9.8.hex:i


avrdude: Version 7.2
         Copyright the AVRDUDE authors;
         see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

         System wide configuration file is C:\Users\kreefd\Desktop\gloves\FreedomWavePD\Software\FreedomWavePD-0.9.8\avrdude.conf

         Using Port                    : 4
         Using Programmer              : arduino
         Overriding Baud Rate          : 57600
avrdude ser_open() error: cannot open port 4: Das System kann die angegebene Datei nicht finden.

avrdude main() error: unable to open programmer arduino on port 4


avrdude done.  Thank you.
```

I have now soldered everything except the DRV2605 as i am waiting for arrival.
Would it be possible to see already something on the screen , expected that the arduino was flashed correctly ?

Thank in you advance

Kind Regards
Kreefd

**Comment by kreefd** [comment]
Great News ,
 can't believe it was the syntax of the command.

avrdude -C avrdude.conf -v -patmega328p -carduino **-P COM4** -b 57600 -D -U flash:w:FreedomWavePD-0.9.8.hex:i

so when i use **-P COM4** and not -P4 or -p4 it works. i can see the FreedomWavePD Ver.0.9.9 *6731* on the display now and can scroll the menu with the controller.

**Comment by RChadwick7** [comment]
I'm glad you figured out the syntax. I'll put it on my to-do list to make it more clear.
